### PR TITLE
Create a "Value" field which represents how much a litre of liquid costs, and make "Cost-Effectiveness" more clear.

### PR DESCRIPTION
**Pull request by ArdvarkDev**
As said in title.

### CODE REVIEW

**Comment by malcolmseyd** [comment]
Hey, thanks for the interest in my project!

I think this PR needs a bit more justification, since I'm not sure I understand the intention of this change. As far as I understand, the `value` column represents $/L of fluid, but I'm not sure what your intention is by adding this. What problem does it solve?

**Comment by ArdvarkDev** [comment]
Put simply, I think that the `value` column is needed because people generally would like something cheap to drink, without the specific goal of becoming hammered at the lowest cost. Combining the `value` column with the filtering system allows one to find the best value of beer, wine, etc. within a given price range of fluid.

I found your project fun and interesting but felt like most people aren't necessarily optimizing for mL of pure ethanol, and would prefer to find something to pair with dinner or to have a drink after school/work.

**Comment by malcolmseyd** [comment]
Fair enough, I think this is a good idea. I'm gonna make some changes to the naming because I think "value" is a bit generic, but otherwise I appreciate the contribution and this looks pretty good to merge!

**Comment by malcolmseyd** [comment]
Okay I renamed it to "drink value", how do you feel about this? I think it's a bit more consistent with the "alcohol value" (previously "cost-effectiveness) that was already there.

image

**Comment by ArdvarkDev** [comment]
A few things:

1. I think that "Drink Value" and "Alcohol Value" are poor names and should be replaced with "Price" and "Alcohol Price" respectively
2. "Price" should be renamed to "Unit Price" or "Item Price" to better reflect what it represents and to not collide with my above suggestion
3. Return the units to reside beside the numbers, to keep in line with the rest of the values, and so that scrolling doesn't turn them into meaningless numbers.
4. Change the units back to $ / L, because no one is buying alcohol in mL increments, and I believe to be a more understandable number. mL / $ can make sense for alcohol price because it is a fairly low number and isn't something one would be looking for litres of ($ / mL or $ / dL could also be done).

Dollars already have a fractional component, while parsing decimals of a mL is odd, so I think the last two units should be normalized to a full L/dL/cL/mL.

**Comment by ArdvarkDev** [comment]
Or perhaps "Alcohol Price" could be "Ethanol Price" to avoid confusion

**Comment by malcolmseyd** [comment]
1. I disagree. Both are units "per dollar", and I think "value" is a good word to describe that.
2. "Price" currently represents the overall price of the item, which I think is a good name. I feel like "unit price" implies price per unit which would not be correct here.
3. I don't think that's necessary, the units can stay at the top. Maybe a sticky header would help the user keep context? I'd rather keep the units in the header just to keep the table contents cleaner tbh, even though it's inconsistent with the rest of the table, because "mL alcohol/$" just doesn't look good on every line.
4. If we switch to L/$ then all values are <1, which I personally just don't like.
5. I don't think "Ethanol" is a great word to use when talking about something you'd drink. I see where you're coming from, but I feel like "Alcohol" makes sense in context and doesn't sound as scary to drink.

I appreciate the feedback, but I think I'm just gonna go ahead and merge this as-is. I'm pretty happy with the improvements that this PR makes, and while I think a lot of your additional suggestions have good ideas, I don't find it necessary to implement or decide as part of this change.

Let's ship it!

**Pull request merged**
